// Generated by https://quicktype.io

export interface UIModelData {
    new:  New;
    edit: Edit;
}

export interface Edit {
    id:    number;
    title: string;
}

export interface New {
    title: string;
}

